# docker-compose.yml
version: "3"

services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=udapeople-prod
    ports:
      - "5532:5432"
